### ISSUE TITLE
Does not work with Elm 0.12

### ISSUE THREAD

**Issue by spanners** [thSoft/elm-lib#1]
I am sure you know this. I don't feel this is an "issue", but simply wished to message you -- 

I am trying to port StampTogether to elm-runtime-0.12 myself in my own fork:

https://github.com/spanners/elm-lib/blob/master/StampTogether/Main.elm

But I get the following error when running `elm --make Main.elm`: 

```
elm: bad ADT got to port generation code
```
- Are you planning on porting StampTogether/Chat to 0.12? 
- Do you have suggestions as how to fix this bug?

**Comment by thSoft** [comment]
Yes, I am fully aware that I should port this to the new FFI introduced in 0.11. Unfortunately, currently I don't have time even to support your efforts, but I am very grateful that you are willing to help. I'm going to look into it in an indefinite amount of time...

2014.03.30. dátummal, 20:04 időpontban Simon Buist notifications@github.com írta:

**Comment by thSoft** [comment]
Thank you @spanners and @evancz, I migrated the stamping example in https://github.com/thSoft/elm-lib/commit/c0a11b49c9fc17360171c3bf54a69e9e90e894ee. There was a module name mismatch, which is not statically checked. :) Unfortunately the chat example would require more work due to the updated Graphics.Input library, so stay tuned...
